# Generated by Django 5.2 on 2025-04-17 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupavailability_soloavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupavailability',
            options={'ordering': ['week_start', 'day', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='soloavailability',
            options={'ordering': ['week_start', 'day', 'start_time']},
        ),
        migrations.AlterField(
            model_name='groupavailability',
            name='week_start',
            field=models.DateField(help_text='Sunday of the week'),
        ),
        migrations.AlterField(
            model_name='soloavailability',
            name='week_start',
            field=models.DateField(help_text='Sunday of the week'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_of_study', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th+ Year')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
