# Generated by Django 5.2 on 2025-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupavailability',
            name='repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soloavailability',
            name='repeated',
            field=models.BooleanField(default=False),
        ),
    ]
