# Generated by Django 5.2 on 2025-04-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soloavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='soloavailability',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='GroupAvailability',
        ),
        migrations.DeleteModel(
            name='SoloAvailability',
        ),
    ]
