ervices:
  - type: web
    name: studysync
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn studysync.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: studysync.settings                               
      - key: PYTHON_VERSION
        value: 3.11.11

