# Generated by Django 5.2 on 2025-04-17 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('university', models.CharField(choices=[('tel_aviv', 'Tel Aviv University'), ('hebrew', 'Hebrew University of Jerusalem'), ('technion', 'Technion – Israel Institute of Technology'), ('haifa', 'University of Haifa'), ('ben_gurion', 'Ben-Gurion University'), ('open', 'Open University'), ('bar_ilan', 'Bar-Ilan University'), ('yafo', 'The Academic College of Tel Aviv–Yaffo'), ('sapir', 'Sapir Academic College'), ('college_management', 'College of Management'), ('shenkar', 'Shenkar College of Engineering, Design and Art'), ('beit_berl', 'Beit Berl College'), ('ruppin', 'Ruppin Academic Center'), ('emek_yizrael', 'Jezreel Valley College')], max_length=100)),
                ('year', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th+ Year')])),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
